INSERT
  INTO  "DIM_PROJECT_NAME"."DIM_PROJECT_NAME_TABLE" ("AGREEMENT_NAME","PROJECT_NAME","BUSINESS_TYPE_NM","ENGAGEMENT_CREATED_BY","DOU_COUNTRY","DELIVERY_MANAGER")
  VALUES(
NULL,               	--AGREEMENT_NAME  VARCHAR(1000)  
NULL,               	--PROJECT_NAME  VARCHAR(1000)  
NULL,               	--BUSINESS_TYPE_NM  VARCHAR(50)  
NULL,               	--ENGAGEMENT_CREATED_BY  VARCHAR(100)  
NULL,               	--DOU_COUNTRY  VARCHAR(50)  
NULL                	--DELIVERY_MANAGER  VARCHAR(50)  
);
